### ISSUE TITLE
Any chance of a less version? 

### ISSUE THREAD

**Issue by eliotstocker** [dudeofawesome/MaterialCSS#1]
Would love to see a less version alongside the scss :) awesome work so far!

**Comment by dudeofawesome** [comment]
Absolutely! (I just need to learn LESS first)

**Comment by eliotstocker** [comment]
its very similar to SCSS so shouldn't be too hard :) also what license are you releasing this under?

—

**Comment by dudeofawesome** [comment]
Alright, I just pushed the LESS version in commit 25855123d26c22ecd70e7768ff41551d28a5829d
