### ISSUE TITLE
Semantics of collection headers.

### ISSUE THREAD

**Issue by jamesmackinnon** [dudeofawesome/MaterialCSS#3]
Having the header of a list be a list item (li) seems like a poor choice semantically since it is a title describing the contents of the list, and not an actual part of the collection.

I'm aware that standards do not condone non-<li> direct children of ul/ol, but hopefull there's a way to seperate things out a bit more without an additional wrapper div?

**Comment by dudeofawesome** [comment]
I'm not sure what part you're talking about? Are you looking at the HTML for the demo page?

**Comment by jamesmackinnon** [comment]
I'm an idiot, added issue for incorrect github repo. Sorry.
